# Generated by Django 2.0.13 on 2019-07-11 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190711_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
    ]
