# Generated by Django 2.0.13 on 2019-07-11 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190711_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
    ]
