# Generated by Django 2.0.13 on 2019-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_reservation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='サンプル項目1 日付'),
        ),
    ]
