# Generated by Django 2.0.13 on 2019-08-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='タイトル'),
        ),
    ]
