# Generated by Django 2.0.13 on 2019-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190807_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='memo',
            field=models.CharField(default=1, max_length=255, verbose_name='メモ'),
        ),
    ]
