# Generated by Django 2.0.13 on 2019-08-16 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='memo',
            field=models.TextField(default=1, max_length=500, verbose_name='メモ'),
        ),
    ]
