# Generated by Django 2.0.13 on 2019-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190816_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='show_flag',
            field=models.CharField(default=1, max_length=50, verbose_name='表示フラグ'),
        ),
    ]
