# Generated by Django 2.0.13 on 2019-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0002_auto_20191009_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgame',
            name='receive_error',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
