# Generated by Django 2.0.13 on 2019-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0003_cgame_receive_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgame',
            name='net',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cgame',
            name='net_error',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
