# Generated by Django 2.0.13 on 2019-10-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0005_auto_20191009_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgame',
            name='games',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
