# Generated by Django 2.0.13 on 2019-10-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0007_remove_cgame_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmatch',
            name='author',
        ),
    ]
