# Generated by Django 2.0.13 on 2019-10-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0008_remove_cmatch_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgame',
            name='second',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='cgame',
            name='second_error',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
